version: "3.8"

services:
  nginx:
    build:  requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html  # Cartella locale => Cartella nel container
      - ${CERTS_VOLUME}:/etc/ssl/certs
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - inception_net
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - ${WP_VOLUME}:/var/www/html
    env_file:
      - .env
    networks:
      - inception_net
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ${MARIADB_VOLUME}:/var/lib/mysql
    networks:
      - inception_net
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mariadb-data:

networks:
  inception_net:
    driver: bridge
