services:
  nginx:
    container_name: nginx
    build:  requirements/nginx/.
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - inception_net
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    restart: always
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    networks:
      - inception_net
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception_net
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      timeout: 20s
      retries: 10

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lotrapan/data/wordpress
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lotrapan/data/mariadb

networks:
  inception_net:
    driver: bridge
