services:
  nginx:
    container_name: nginx
    build:  requirements/nginx/.
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - inception_net
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    restart: always
    volumes:
      - wordpress-data:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    networks:
      - inception_net
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception_net

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lotrapan/data/wordpress
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lotrapan/data/mariadb

networks:
  inception_net:
    driver: bridge
